import '@/styles/tailwind.css'
import Navbar from '@/components/navbar'
import { ConfigProvider } from '@/components/stores/config'
import { getPageMap } from 'nextra/page-map'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let pageMap = await getPageMap()

  return (
    <html lang="en">
      <body>
        <ConfigProvider navbar={<Navbar />} pageMap={pageMap}>
          {children}
        </ConfigProvider>
      </body>
    </html>
  )
}
