/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Application: typeof import('./src/components/Application.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PageControls: typeof import('./src/components/PageControls.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
