export default {
  'plugin-document-manager': 'Document Manager',
  'plugin-viewport': 'Viewport',
  'plugin-scroll': 'Scroll',
  'plugin-render': 'Render',
  'plugin-tiling': 'Tiling',
  'plugin-thumbnail': 'Thumbnail',
  'plugin-annotation': 'Annotation',
  'plugin-selection': 'Selection',
  'plugin-zoom': 'Zoom',
  'plugin-rotate': 'Rotate',
  'plugin-print': 'Print',
  'plugin-export': 'Export',
  'plugin-spread': 'Spread',
  'plugin-pan': 'Pan',
  'plugin-capture': 'Capture',
  'plugin-redaction': 'Redaction',
  'plugin-i18n': 'Internationalization',
  'plugin-view-manager': 'View Manager',
  'plugin-commands': 'Commands',
  'plugin-layout-analysis': 'Layout Analysis',
}
